/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    QBadge: typeof import('quasar')['QBadge']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QCheckbox: typeof import('quasar')['QCheckbox']
    QDate: typeof import('quasar')['QDate']
    QDialog: typeof import('quasar')['QDialog']
    QFile: typeof import('quasar')['QFile']
    QIcon: typeof import('quasar')['QIcon']
    QInput: typeof import('quasar')['QInput']
    QItemSection: typeof import('quasar')['QItemSection']
    QOptionGroup: typeof import('quasar')['QOptionGroup']
    QPopupProxy: typeof import('quasar')['QPopupProxy']
    QRadio: typeof import('quasar')['QRadio']
    QSelect: typeof import('quasar')['QSelect']
    QTab: typeof import('quasar')['QTab']
    QTabPanel: typeof import('quasar')['QTabPanel']
    QTabPanels: typeof import('quasar')['QTabPanels']
    QTabs: typeof import('quasar')['QTabs']
    QTime: typeof import('quasar')['QTime']
    QuizCreateAddOn: typeof import('./src/components/QuizCreateAddOn.vue')['default']
    QuizCreateAddOnPage: typeof import('./src/components/QuizCreateAddOnPage.vue')['default']
    QuizCreateContents: typeof import('./src/components/QuizCreateContents.vue')['default']
    QuizCreateFilter: typeof import('./src/components/QuizCreateFilter.vue')['default']
    QuizCreatePreview: typeof import('./src/components/QuizCreatePreview.vue')['default']
    QuizCreateQuerys: typeof import('./src/components/QuizCreateQuerys.vue')['default']
    QuizCreateQuerysType: typeof import('./src/components/QuizCreateQuerysType.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
